from enum import Enum


class CommunityBoardDistrictEnum(Enum):
    BRONX_1 = 'Bronx 1'
    BRONX_2 = 'Bronx 2'
    BRONX_3 = 'Bronx 3'
    BRONX_4 = 'Bronx 4'
    BRONX_5 = 'Bronx 5'
    BRONX_6 = 'Bronx 6'
    BRONX_7 = 'Bronx 7'
    BRONX_8 = 'Bronx 8'
    BRONX_9 = 'Bronx 9'
    BRONX_10 = 'Bronx 10'
    BRONX_11 = 'Bronx 11'
    BRONX_12 = 'Bronx 12'
    BROOKLYN_1 = 'Brooklyn 1'
    BROOKLYN_2 = 'Brooklyn 2'
    BROOKLYN_3 = 'Brooklyn 3'
    BROOKLYN_4 = 'Brooklyn 4'
    BROOKLYN_5 = 'Brooklyn 5'
    BROOKLYN_6 = 'Brooklyn 6'
    BROOKLYN_7 = 'Brooklyn 7'
    BROOKLYN_8 = 'Brooklyn 8'
    BROOKLYN_9 = 'Brooklyn 9'
    BROOKLYN_10 = 'Brooklyn 10'
    BROOKLYN_11 = 'Brooklyn 11'
    BROOKLYN_12 = 'Brooklyn 12'
    BROOKLYN_13 = 'Brooklyn 13'
    BROOKLYN_14 = 'Brooklyn 14'
    BROOKLYN_15 = 'Brooklyn 15'
    BROOKLYN_16 = 'Brooklyn 16'
    BROOKLYN_17 = 'Brooklyn 17'
    BROOKLYN_18 = 'Brooklyn 18'
    MANHATTAN_1 = 'Manhattan 1'
    MANHATTAN_2 = 'Manhattan 2'
    MANHATTAN_3 = 'Manhattan 3'
    MANHATTAN_4 = 'Manhattan 4'
    MANHATTAN_5 = 'Manhattan 5'
    MANHATTAN_6 = 'Manhattan 6'
    MANHATTAN_7 = 'Manhattan 7'
    MANHATTAN_8 = 'Manhattan 8'
    MANHATTAN_9 = 'Manhattan 9'
    MANHATTAN_10 = 'Manhattan 10'
    MANHATTAN_11 = 'Manhattan 11'
    MANHATTAN_12 = 'Manhattan 12'
    QUEENS_1 = 'Queens 1'
    QUEENS_2 = 'Queens 2'
    QUEENS_3 = 'Queens 3'
    QUEENS_4 = 'Queens 4'
    QUEENS_5 = 'Queens 5'
    QUEENS_6 = 'Queens 6'
    QUEENS_7 = 'Queens 7'
    QUEENS_8 = 'Queens 8'
    QUEENS_9 = 'Queens 9'
    QUEENS_10 = 'Queens 10'
    QUEENS_11 = 'Queens 11'
    QUEENS_12 = 'Queens 12'
    QUEENS_13 = 'Queens 13'
    QUEENS_14 = 'Queens 14'
    STATEN_ISLAND_1 = 'Staten Island 1'
    STATEN_ISLAND_2 = 'Staten Island 2'
    STATEN_ISLAND_3 = 'Staten Island 3'


COMMUNITY_BOARD_DISTRICT_LIST = [c.value for c in CommunityBoardDistrictEnum]
