"""submission table

Revision ID: 143f81c3bba3
Revises: 
Create Date: 2019-02-25 21:25:17.891423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143f81c3bba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subtitles', postgresql.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('additional_creators', postgresql.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('subjects', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('date_published', sa.Date(), nullable=False),
    sa.Column('report_type', sa.Enum('ADJUDICATIONS_DECISIONS', 'AUDIT_REPORT', 'BROCHURES', 'BUDGET_FINANCE', 'BULLETINS', 'CALENDARS', 'DATA_STATISTICS', 'DIRECTIVES', 'ENVIRONMENTAL_IMPACT_STATEMENTS_DRAFT', 'ENVIRONMENTAL_IMPACT_STATEMENTS_FINAL', 'EXECUTIVE_ORDERS', 'GUIDES', 'LAWS_LEGISLATION', 'MANUALS_DIRECTORIES', 'MINUTES', 'NEWSLETTERS_OTHER_SERIAL_PUBLICATIONS', 'OTHER', 'PLANS', 'PRESS_RELEASES', 'PROCEEDINGS', 'REPORTS_ANNUAL', 'REPORTS_BIENNIAL', 'REPORTS_MONTHLY', 'REPORTS_WEEKLY', 'REPORTS_OTHER_CONSULTANT_STAFF', 'STUDIES', name='reporttypeenum'), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('fiscal_years', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('calendar_years', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('boroughs', postgresql.ARRAY(sa.Enum('BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN_ISLAND', name='boroughenum')), nullable=True),
    sa.Column('school_districts', postgresql.ARRAY(sa.Enum('DISTRICT_1', 'DISTRICT_2', 'DISTRICT_3', 'DISTRICT_4', 'DISTRICT_5', 'DISTRICT_6', 'DISTRICT_7', 'DISTRICT_8', 'DISTRICT_9', 'DISTRICT_10', 'DISTRICT_11', 'DISTRICT_12', 'DISTRICT_13', 'DISTRICT_14', 'DISTRICT_15', 'DISTRICT_16', 'DISTRICT_17', 'DISTRICT_18', 'DISTRICT_19', 'DISTRICT_20', 'DISTRICT_21', 'DISTRICT_22', 'DISTRICT_23', 'DISTRICT_24', 'DISTRICT_25', 'DISTRICT_26', 'DISTRICT_27', 'DISTRICT_28', 'DISTRICT_29', 'DISTRICT_30', 'DISTRICT_31', 'DISTRICT_32', 'DISTRICT_75', 'DISTRICT_79', name='schooldistrictenum')), nullable=True),
    sa.Column('community_board_districts', postgresql.ARRAY(sa.Enum('BRONX_1', 'BRONX_2', 'BRONX_3', 'BRONX_4', 'BRONX_5', 'BRONX_6', 'BRONX_7', 'BRONX_8', 'BRONX_9', 'BRONX_10', 'BRONX_11', 'BRONX_12', 'BROOKLYN_1', 'BROOKLYN_2', 'BROOKLYN_3', 'BROOKLYN_4', 'BROOKLYN_5', 'BROOKLYN_6', 'BROOKLYN_7', 'BROOKLYN_8', 'BROOKLYN_9', 'BROOKLYN_10', 'BROOKLYN_11', 'BROOKLYN_12', 'BROOKLYN_13', 'BROOKLYN_14', 'BROOKLYN_15', 'BROOKLYN_16', 'BROOKLYN_17', 'BROOKLYN_18', 'MANHATTAN_1', 'MANHATTAN_2', 'MANHATTAN_3', 'MANHATTAN_4', 'MANHATTAN_5', 'MANHATTAN_6', 'MANHATTAN_7', 'MANHATTAN_8', 'MANHATTAN_9', 'MANHATTAN_10', 'MANHATTAN_11', 'MANHATTAN_12', 'QUEENS_1', 'QUEENS_2', 'QUEENS_3', 'QUEENS_4', 'QUEENS_5', 'QUEENS_6', 'QUEENS_7', 'QUEENS_8', 'QUEENS_9', 'QUEENS_10', 'QUEENS_11', 'QUEENS_12', 'QUEENS_13', 'QUEENS_14', 'STATEN_ISLAND_1', 'STATEN_ISLAND_2', 'STATEN_ISLAND_3', name='communityboarddistrictenum')), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
